name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build All The Things
      run: |
        echo "done!"

  deploy_dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: dev
    steps:
    - name: Deploy to dev
      run: |
        echo "done!"

  deploy_prod:
    name: Deploy to proid
    runs-on: ubuntu-latest
    needs: [build, deploy_dev]
    environment:
      name: prod
    steps:
    - name: Deploy to prod
      run: |
        echo "done!"
