name: Tag

on:
  workflow_dispatch:

jobs:
  set-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        # tell the action to fetch tags
        fetch-depth: 0
    - id: determine_tag
      name: Determine Tag
      run: |
        tag.sh $GITHUB_SHA
    - name: Create Tag
      if: ${{ steps.determine_tag.outputs.tag_name != '' }}
      uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ steps.determine_tag.outputs.tag_name }}
        commit_sha: ${{ github.sha }}